FROM node:20-alpine

WORKDIR /app

# Instalar dependencias
COPY package*.json ./
RUN npm install

# Copiar código fuente
COPY . .

# Exponer puerto de Vite
EXPOSE 3000

# Hot reload con Vite
CMD ["npm", "run", "dev", "--", "--host"]